# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[38;2;210;210;0m'
YELLOW_BOLD='\033[1;33m'
NC='\033[0m' # No Color + No Text Style
WHITE='\033[0;37m'

# Network Colors used by ip command
IPv4Color='\033[1;35m'
IPv6Color='\033[1;34m'
MAC_ADDR="$YELLOW_BOLD"

# Text Style
BOLD='\033[1m'
DIM='\033[2m'
ITALIC='\033[3m'
UNDERLINE='\033[4m'